backend:
  name: github
  repo: cfarm/design-manual
  branch: gh-pages
  site_domain: cfarm.github.io

publish_mode: editorial_workflow

media_folder: "images/uploads"

collections:
  - name: "navigation"
    label: "Navigation"
    editor:
      preview: true
    files:
      - label: "Primary navigation"
        name: "navigation-primary"
        file: "_data/navigation-primary.yml"
        fields:
          - label: "Primary navigation links"
            name: "mainnav"
            widget: "list"
            fields:
              - {label: "Text", name: "text", widget: "string"}
              - {label: "URL", name: "url", widget: "string"}
              - {label: "Internal link?", name: "internal", widget: "boolean"}
      - label: "Secondary navigation"
        name: "navigation-secondary"
        file: "_data/navigation-secondary.yml"
        fields:
          - label: "Secondary navigation links"
            name: "secondarynav"
            widget: "list"
            fields:
              - {label: "Text", name: "text", widget: "string"}
              - {label: "URL", name: "url", widget: "string"}
              - {label: "Internal link?", name: "internal", widget: "boolean"}
              - {label: "Category", name: "category", widget: "select", options: ["Best practices", "Brand guidelines", "Global elements", "Page components", "Data visualization"]}
  - name: "page-component" # Used in routes, e.g., /admin/collections/blog
    label: "Page components" # Used in the UI
    label_singular: "Page component"
    folder: "page-components/" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {name: "layout", value: "page", widget: "hidden"}
      - {name: "category", value: "Page components", widget: "hidden"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Implementation status", name: "implementation-status", widget: "select", options: [ { label: "Proposed", value: "proposed" }, { label: "In progress", value: "in-progress" }, {label: "Beta", value: "beta" }, {label: "Released", value: "released" } ] }
      - {label: "Description", name: "description", widget: "markdown"}
      - {label: "HTML snippet", name: "html-snippet", widget: "string"}
      - {label: "Jinja2 snippet", name: "jinja2-snippet", widget: "string"}
      - label: "Section"
        name: "section"
        widget: "list"
        required: false
        fields:
          - {label: 'Section heading', name: section-heading, widget: string, default: "Section heading text goes here"}
          - label: 'Section content'
            name: section-content
            widget: markdown
      - {label: "Body", name: "body", widget: "markdown", required: false}
